#pragma once

#include <ntddk.h>

#define FIDRA_DEVICE_TYPE FILE_DEVICE_UNKNOWN

#define IOCTL_READ_MEMORY       CTL_CODE(FIDRA_DEVICE_TYPE, 0x800, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_WRITE_MEMORY      CTL_CODE(FIDRA_DEVICE_TYPE, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_GET_BASE          CTL_CODE(FIDRA_DEVICE_TYPE, 0x802, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_GET_PROCESS_LIST  CTL_CODE(FIDRA_DEVICE_TYPE, 0x803, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_GET_MODULES       CTL_CODE(FIDRA_DEVICE_TYPE, 0x804, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_READ_PHYSICAL     CTL_CODE(FIDRA_DEVICE_TYPE, 0x805, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_WRITE_PHYSICAL    CTL_CODE(FIDRA_DEVICE_TYPE, 0x806, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_GET_CR3           CTL_CODE(FIDRA_DEVICE_TYPE, 0x807, METHOD_BUFFERED, FILE_ANY_ACCESS)
